### ISSUE TITLE
关于旧版本适配问题

### ISSUE THREAD

**Issue by DMCKirito** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#104]
目前配置为 MSI-360 迫击炮钛金板 + i59500 + MSI GTX1060
因为使用的是N卡，所以想用旧的10.13.6版本，请问大大这个EFI能直接用么

**Comment by andot** [comment]
我没试过，我也不知道。

**Comment by DMCKirito** [comment]
感谢大大回复，昨天之前没看到对应的issue~

**Comment by andot** [comment]
嗯，你试试看吧，不行的话，大不了只用核显。
