### ISSUE TITLE
大佬有加睿频的打算吗？

### ISSUE THREAD

**Issue by nathan-code** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#107]
突然发现大佬转OC了，惊喜，感谢。

这个OC EFI似乎没有加CPUFriend，也就是说没有睿频。大佬有打算研究一下吗？谢谢~

**Comment by andot** [comment]
如果你的 CPU 是 9 代 i5、i7 或 i9 的话，需要 CPUFriend 的话自己加就行了，但是 [GeQ1an](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI) 说 iMac19,2 这个机型不支持 CPUFriend，所以我就没加，毕竟 i7-8700 不支持超频，硬给改成 iMac19,1 上睿频到 5.0G 的话，我怕把 CPU 给烧了😂。

反正不加 CPUFirend，我的 CPU 频率也会在 1.6G 到 4.6G 范围波动，这已经是正常的频率范围了，所以我觉得什么都不用加。

**Comment by nathan-code** [comment]
> [GeQ1an](https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI) 说 iMac19,2 这个机型不支持 CPUFriend，所以我就没加，毕竟 i7-8700 不支持超频，硬给改成 iMac19,1 上睿频到 5.0G 的话，我怕把 CPU 给烧了😂。
> 
> 反正不加 CPUFirend，我的 CPU 频率也会在 1.6G 到 4.3G 范围波动，这已经是正常的频率范围了，所以我觉得什么都不用加。
> 
> ![image](https://user-images.githubusercontent.com/232161/86553681-fc201680-bf7d-11ea-862e-376647721ca6.png)
> 
> 如果你的 CPU 是 9 代 i5、i7 或 i9 的话，需要 CPUFriend 的话，可以把机型改成 iMac19,1 然后自己加就行了。

好的，谢谢大佬回复。我的是8400，哈哈，看来没必要折腾了，现在也挺好。感谢~~
