### ISSUE TITLE
LastBootedVolume 不生效

### ISSUE THREAD

**Issue by zou2699** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#11]
您好，我这里遇到个问题，默认使用EmuVariableUefi.efi时， LastBootedVolume不生效，不能记住上次的启动分区；
去除EmuVariableUefi.efi，LastBootedVolume可以生效，能记住上次启动的分区，但是这时，隔空投送又不能用了。

**Comment by YIZHEV** [comment]
你是什么网卡？

**Comment by zou2699** [comment]
添加rc.scripts就可以了
