### ISSUE TITLE
10.15.16 睡眠唤醒显卡疯转一会后恢复

### ISSUE THREAD

**Issue by OysterQAQ** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#115]
每次睡眠唤醒显卡总是疯转一会

**Comment by OysterQAQ** [comment]
8700+rx480

**Comment by andot** [comment]
我也是，除了天冷的时候。

**Comment by OysterQAQ** [comment]
用另一个老哥efi之前好像不会 不过他的10.15.16睡眠唤醒不能用

**Comment by andot** [comment]
哦，你已经成功升级到 10.15.6 了？对了，你可以试一试升级到最新的 OC 0.6.0 版本：
https://github.com/williambj1/OpenCore-Factory/releases

**Comment by OysterQAQ** [comment]
哈哈 不太会升级 用着你的吧

**Comment by andot** [comment]
升级很简单啊，对应的文件都替换一下就行了。

**Comment by OysterQAQ** [comment]
直接拖进去替换吗

**Comment by andot** [comment]
一个一个文件替换，因为有些是不需要的。还有些是空目录，你拖目录进去替换可能会覆盖掉原来的内容。

**Comment by OysterQAQ** [comment]
ok
