### ISSUE TITLE
开机 clover 引导问题

### ISSUE THREAD

**Issue by YIZHEV** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#12]
问题描述我有点不知道怎么描述，我和你几乎一致。前半个月使用你的配置没有任何问题，等我升级到10.15.1之后就发现关机之后第一次开机总是出现clover的非UI界面，而且这样开机进入系统之后，屏幕一直闪烁。然后关机重启第二次就好了，正常进入系统。
请问一下这个问题有遇到过嘛，我现在是完全不知道怎么解决了。

![CE43555C-EF7A-4B8E-BFAF-0849AFB3D7DC](https://user-images.githubusercontent.com/23192538/67781160-09f1d380-faa2-11e9-8ebd-457b5036fe11.jpeg)

**Comment by andot** [comment]
我刚把驱动更新到最新版本，同时把系统更新到了 10.15.1，目前没有遇到你说的这个问题。

**Comment by YIZHEV** [comment]
这个问题找到原因了，但是代价有点大了。之前的LG 29WK600 显示器一直是这个问题，实在是解决不了了就换了个4k显示器，KOIOS的垃圾显示器，但是比例是16:9 的正常比例，所有东西完美了。哈哈
