### ISSUE TITLE
请问关于EFI与镜像的关联问题

### ISSUE THREAD

**Issue by ShawLocke** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#123]
andot，你好，问题有点长，先谢谢。

电脑配置：微星B360M迫击炮，i5-9600kf，蓝宝石RX570，老SSD1 SN750 500G(安装的是Win10)，新SSD: RC10 500G (没有任何系统)
需求：往新SSD中装黑苹果。

往主板上安装新SSD的问题：第一次装上去后没有识别到，然后我重新插拔了一下，能够正常识别了。

---

我下载了黑果小兵10.15.7的镜像: <https://blog.daliansky.net/macOS-Catalina-10.15.7-19H2-Release-version-with-Clover-5122-original-image-Double-EFI-Version-UEFI-and-MBR.html>，制作了安装盘。

在DiskGenius删除安装盘中EFI分区中的EFI文件夹，下载你的EFI，将EFI文件夹拖入到EFI分区。然后重启电脑，结果引导界面怎么都出不了，直接进了Win10。如果启动时，按方向键左右键，会出来2个选项，1个是U盘，点进去了PE系统，1个是硬盘，里面是Win10系统。我也试过，如果不替换EFI，直接用黑果小兵的镜像，是能正常出现引导界面的。请问这是什么问题？我是不是得去下载黑锅小兵的这个带有OC启动的镜像版本: <https://blog.daliansky.net/WeChat-First-macOS-Catalina-10.15.7-19H2-official-version-Clover-5122-OC-WEPE-supports-both-INTEL-and-AMD-original-images.html>

---

我想起来今年早些时候用过你的EFI（你以前的EFI，我有保存），然后下载黑果小兵的10.15.4镜像，能够正常出现引导界面，也顺利安装了，也将U盘中的EFI拖到了新SSD中了，拔掉U盘，重启会直接进入Win10。我知道问题出在：BIOS中的引导顺序里没有新SSD(黑果系统)，只有老SSD，但存储中显示的是：M2_1是老SSD，M2_2是新SSD，这说明主板能识别出来SSD，只是新SSD在启动顺序中无法出现，请问可能是什么问题？是不是应该尝试将BIOS的设置恢复到默认值，如果还是不行，是不是应该将BIOS升级到最新版，我目前还不是最新版的BIOS。

---
如果有T群联系方式就好了，再次感谢，谢谢你EFI。

**Comment by andot** [comment]
Bios里面可以调整启动磁盘的顺序的。

**Comment by ShawLocke** [comment]
主要是启动磁盘中根本没有新SSD那一项，晚上我回去试试重置看一下

**Comment by ShawLocke** [comment]
使用微星B360M迫击炮钛金版的注意一下哈，2个SSD如果只能显示一个在启动顺序中，请到高级模式/Settings/启动，滚动到最下面，点击UEFI硬盘BBS优先级，启动选项1选为mac所在的SSD，保持后会自动重启。

补充：我之前提到用小马哥的EFI替换黑果小兵10.15.7镜像后，设置U盘为第一启动项，重启后一直看不到引导界面，实际操作需要将U盘要重新插拔一下。

最后谢谢小马哥的EFI，我现在用的是你最新的EFI，镜像是黑果小兵的10.15.7
