### ISSUE TITLE
在线等一个big sur测试

### ISSUE THREAD

**Issue by OysterQAQ** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#124]
大佬们 可以升级吗

**Comment by andot** [comment]
今天才刚出正式版，还没测试，不知道。

**Comment by ChristianSwift** [comment]
插眼

**Comment by c937091690** [comment]
最新的EFI可升big sur。直升暂时没遇到什么问题

**Comment by logycoconut** [comment]
插个眼再说

**Comment by ChristianSwift** [comment]
> 最新的EFI可升big sur。直升暂时没遇到什么问题

Clover还是OC？

**Comment by OysterQAQ** [comment]
> 最新的EFI可升big sur。直升暂时没遇到什么问题

睡眠什么都正常吗

**Comment by c937091690** [comment]
> > 最新的EFI可升big sur。直升暂时没遇到什么问题
> 
> Clover还是OC？

OC

**Comment by c937091690** [comment]
> > 最新的EFI可升big sur。直升暂时没遇到什么问题
> 
> 睡眠什么都正常吗

睡眠正常，9400+rx580

**Comment by guange2015** [comment]
有人尝试过clover升big sur吗，我换oc会卡白苹果。

**Comment by OysterQAQ** [comment]
已经升级 目前发现唯一的问题是2k副屏hdpi失效 重新执行脚本后正常
