### ISSUE TITLE
显卡过大无法装下无线网卡有什么解决办法吗？

### ISSUE THREAD

**Issue by fg4084** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#15]
买的蓝宝石590，结果真的发现装不下无线网卡了，不知道有什么解决办法。看到淘宝有卖半栏的网卡，配上pcie延长线不知道怎么样。

**Comment by andot** [comment]
这个我没有试过，我当初的解决办法是把厚的显卡退了，换了一个比较薄的显卡。

**Comment by dec2hex** [comment]
可以插在最下面那根pcie x16插槽上，说明书有说支持x16和x4模式

**Comment by andot** [comment]
@dec2hex 最下面那根pcie x16插槽跟第二个m2插槽冲突，如果装了两个m2硬盘的话，最下面那个pcie x16插槽是用不了的。

**Comment by fg4084** [comment]
> 可以插在最下面那根pcie x16插槽上，说明书有说支持x16和x4模式

如andot所说，我安装了两个m2硬盘

**Comment by fg4084** [comment]
延长线已解决

**Comment by mcdongWang** [comment]
我也是 590 + 无线网卡.

装的时候 故意偏下一点, 躲开了 590的风扇
