### ISSUE TITLE
Clover概率性识别不了USB键盘

### ISSUE THREAD

**Issue by Taosky** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#16]
clover界面有时候识别不出USB键盘，重新插拔之后可以使用，有人碰到过这个情况吗。

**Comment by andot** [comment]
没有遇到过。

**Comment by Taosky** [comment]
BIOS里面有个USB的选项关了之后用了一段时间（默认是开着的），再也没有出现这个问题。

**Comment by ArchFeh** [comment]
插主板上一般不会出现这个问题，插机箱前面会
