### ISSUE TITLE
magic trackpad2 插上usb 之后没有识别（暂未购置无线网卡）

### ISSUE THREAD

**Issue by ripmars** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#19]
暂时未购置无线网卡。临时将触控板通过USB线连接USB接口，系统未检测到触控板，无法使用。
期待回复。

**Comment by andot** [comment]
USB 线不是充电用的吗？

**Comment by ripmars** [comment]
不是只能充电。开启状态插入USB是可以直接当有线触摸板使用的。打开Hackintool 软件之后就可以正常使用了。🤷‍♂️

**Comment by andot** [comment]
原来如此，又学了一招。
