### ISSUE TITLE
970 EVO Plus应该是可以用的

### ISSUE THREAD

**Issue by lclancey** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#20]
19年上半年三星提供了新固件，可以完美黑果了，而且相当稳定
旧硬盘可以升级固件，京东大概6月之后出的新品都是自带新固件的
981依然不行

**Comment by andot** [comment]
这么爽，那以后有便宜的硬盘可以用了。

**Comment by andot** [comment]
啊，刚才看了一下 970 EVO Plus 的价格，一点都不便宜 :<

**Comment by qianyeLC** [comment]
> 啊，刚才看了一下 970 EVO Plus 的价格，一点都不便宜 😅

970evo的升级版 零售市场产品 价格确实贵
981这种OEM产品能黑才好

另外大佬 我现在用这个EFI启动过程还有些毛病 中间倒是流畅。。。我先自己研究下再来发issue。。

**Comment by andot** [comment]
雷克沙、Asgard、海康威视、浦科特 的这些比较便宜，就是不知道装黑苹果效果怎么样

**Comment by voltanlee** [comment]
Pm981做从盘可以正常读写，主盘没敢尝试
