### ISSUE TITLE
B360M 迫击炮的 BIOS 中没有找到 CFG Lock 选项

### ISSUE THREAD

**Issue by GeQ1an** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#25]
> 如果你在 BIOS 里面把 CFG Lock 选项设置为 Disable，那么你还可以用 Clover Configurator 修改配置文件，将 AppleIntelCPUPM 和 内核电源 两个选项的对勾去掉，这样就可以开启原生电源管理了，据说性能会有微小的一点提升。

我在 BIOS 中没有搜到这个选项，请问您是哪个版本的 BIOS？

**Comment by andot** [comment]
最新的2个版本里面都有，这一项比较隐藏，在超频选项里面，点开好几层才能找到，你慢慢找找。
