### ISSUE TITLE
无线网卡bcm94360cd ，蓝牙未识别

### ISSUE THREAD

**Issue by hustyep** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#26]
mac系统是catalina 10.15.2。主要配置是i5 9400f，主板B360 mortar，显卡rx590。其他都很正常，就是蓝牙没有识别，在win10下蓝牙是正常的，不知道是不是usb定制的问题。
还有个小问题是长时间睡眠以后，只能通过机箱电源键唤醒，win10也是这样，不知道是不是需要修改bios电源设置。

**Comment by andot** [comment]
这个 EFI 没有做 USB 定制，用的是万能注入。你可以自己试试用定制 USB 能不能解决。另外，你可以搜一下你那个无线网卡在 Mac 下是不是需要别的驱动补丁才能开启蓝牙什么的，毕竟不同的无线网卡，开启方式都不一样。

**Comment by andot** [comment]
BIOS 里面有一项是 USB 唤醒，设置为的打开，才能用 USB 鼠标或键盘唤醒。

**Comment by hustyep** [comment]
非常感谢，按照你的回复两个问题都已经解决。蓝牙确实需要其他驱动，参考https://github.com/RehabMan/OS-X-BrcmPatchRAM。 睡眠唤醒问题修改修改bios就可以了。
