### ISSUE TITLE
开机苹果logo由大变小

### ISSUE THREAD

**Issue by Hsintao** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#27]
你好 请问4k屏幕 clover的 screen resolution 和UIscale应该设置为多少

**Comment by Hsintao** [comment]
BIOS中CSM需要关闭吗

**Comment by andot** [comment]
CSM 需要关闭（但我的好像默认就是关闭的）
如果你用 HiDPI 就把 UIScale 设置为 2，如果你不用 HiDPI 就把 UIScale 设置为 1。
