### ISSUE TITLE
谁能提供一下efi文件夹的目录格式吗？

### ISSUE THREAD

**Issue by guange2015** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#29]
使用clover configurate mount efi分区后，里面的文件目录。
我直接复制了efi文件夹进去，启动识别不了

/EFI/EFI/CLOVER
/EFI/EFI/BOOT
/EFI/EFI/APPLE

**Comment by andot** [comment]
目录格式没错，你可能没选对启动盘。

**Comment by guange2015** [comment]
用这个复制的方式，是不是无需再安装clover boot什么的

**Comment by andot** [comment]
嗯，直接复制就算安装了

**Comment by andot** [comment]
另外，EFI 目录没有 2 层嵌套，除非第一个 EFI 是你的分区名字。

**Comment by guange2015** [comment]
谢谢，确实如你所说，问题已决。
