### ISSUE TITLE
重启显示器后没有dp信号

### ISSUE THREAD

**Issue by bigdogs** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#3]
感谢大神提供的efi配置， 用了efi后基本上都能正常工作。
就是是发现一个小毛病:
         "关闭显示器开关后， 然后重新打开显示器，发现显示器接收不到任何信号(no dp singal)"
我用的是dp口， 尝试了重新插拔dp线也不行， 最后只能重启

不知道有没有同样遇到过这个问题的朋友:）

**Comment by bigdogs** [comment]
:(， 大神能提供下思路吗

**Comment by andot** [comment]
我这里没有问题，我两台显示器，一个接的dp接口，一个接的hdmi接口，两台显示器关机之后，打开都能接收到信号，我接的是独显的接口。不过我的机型现在是设置为 iMac2019(iMac19,2) 这个机型了，也许跟这个有关？

**Comment by bigdogs** [comment]
我在想想别的办法， 谢谢大神。 可能和核显的某些配置有关

**Comment by andot** [comment]
你用的是核显，不是独显吗？

**Comment by bigdogs** [comment]
嗯， hd630。 尝试过更改启动参数darkwake=8，但是没有效果:(

**Comment by andot** [comment]
你用核显就不要用这个 EFI 了。核显建议用这个：https://github.com/SuperNG6/MSI-B360-10.14.6-EFI

**Comment by bigdogs** [comment]
好的， 谢谢大神
