### ISSUE TITLE
装完windows后，bios中找不到clover的efi分区了

### ISSUE THREAD

**Issue by guange2015** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#31]
按f11，可以选择启动项，而在bios中没有，无法设置。

![WechatIMG2](https://user-images.githubusercontent.com/222455/70963289-00a8de80-20c3-11ea-889c-3c5ceccdcbab.jpeg)

**Comment by andot** [comment]
你系统只有一块硬盘吗？是不是你安装Windows的时候，把MacOS的EFI给覆盖了。

**Comment by andot** [comment]
如果是这样的话，你用MacOS的U盘启动，然后把MacOS的EFI中的文件再放回去就行了。

**Comment by guange2015** [comment]
这个可能是我悲剧的把efi分区搞坏了。
