### ISSUE TITLE
boot 3秒自动进入无效

### ISSUE THREAD

**Issue by guange2015** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#35]
我是双系统，win+mac，配置为默认的
LastBootedVolume 3秒等待时间

**Comment by andot** [comment]
这个问题是 EmuVariableUefi.efi 这个驱动造成的，删掉它就有效了。不过删掉它之后可能对 message 和 facetime 有影响。

**Comment by guange2015** [comment]
已经删了，但是还是没有效果。
是mount后进去删的，还需不需要刷新驱动之类的操作

**Comment by andot** [comment]
不需要刷新驱动，但是可能需要按 F11 清空 Nvram

**Comment by guange2015** [comment]
感谢，再次重启后生效。
