### ISSUE TITLE
关于独显硬解的问题

### ISSUE THREAD

**Issue by derbalkon** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#37]
看到介绍里说

> 这个 EFI 的特点是使用的是 iMacPro1,1 机型，用独显硬解，因此 CPU 有无核显都可以正常工作，且比使用核显硬解更正常。

请问这个 EFI 是怎么实现独显硬解的呢？这里的无核显硬解和有核显硬解有什么不同？
我的机器的 CPU 是 i5-9400，是带核显的，如果想用核显硬解，需不需要对这个 EFI 做什么逆修改呢？

**Comment by lengsen666** [comment]
我一开始没有独立显卡，用的核心显卡硬解。 直接用的楼主的EFI就进系统了。 用的clover修改的三码。机型是iMac19.2. 没做什么其他复杂修改。 开机读条还没有闪，再正常不过了。

**Comment by lengsen666** [comment]
就是需要进主板BIOS，修改默认成集成显卡。

**Comment by derbalkon** [comment]
我想了解的是，这个 EFI 实现无独显硬解的方法会不会对有核显的机器有影响，因为睡眠隔一段时间会自动唤醒，日志里很多 WindowServer (Skylight) 的核显错误提示。

**Comment by andot** [comment]
你有核显的话，就把机型设置为 iMac19,2 就行了。
