### ISSUE TITLE
10.15.2睡眠自动唤醒问题

### ISSUE THREAD

**Issue by qudingDashBoard** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#46]
手动睡眠正常，相关唤醒提醒也都关闭了，但是系统每天早上9点还会准时被唤醒，唤醒后无法自动进入休眠，没找到原因。
直接是10.14升级上来的。

**Comment by derbalkon** [comment]
自动唤醒的问题，打开终端输入命令：log show --last 1d | grep "Wake reason" 看看唤醒原因。

唤醒后无法自动休眠的问题，是因为最新的 macOS Catalina 10.15.2 中，parsec-fbf 会阻止空闲睡眠，在终端输入：launchctl unload -w /System/Library/LaunchAgents/com.apple.parsec-fbf.plist 重启之后就可以在自动唤醒后自动休眠了。

**Comment by qudingDashBoard** [comment]
@derbalkon thanks,我先试试,再观察一天

**Comment by qudingDashBoard** [comment]
今日没再唤醒,正常睡眠.
