### ISSUE TITLE
关于Clover Configurator操作的疑问

### ISSUE THREAD

**Issue by ShawLocke** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#49]
首先谢谢大佬你的EFI，我先下载了黑果小兵的macOS镜像，然后用你的EFI替代了原EFI，然后顺利安装了，目前看起来是完美的。但我刚刚看到你的一段描述：
**“安装前请注意，一定要用 Clover Configurator 重新生成并替换 SMBIOS 部分的内容，否则会因为机器有同一个硬件 ID 而被苹果封锁。”**

我的疑问：
1. Clover Configurator只能在macOS中使用，如果PC还没成功安装macOS，而我手头又没有Mac的话，我怎么使用Clover Configurator? 
2. 这个步骤可不可以在安装完macOS后再操作？如果可以，那达到洗白效果了吗？

期待你的回复，谢谢！

**Comment by andot** [comment]
可以，你安装过程别联网，安装完成之后，没有重新生成 SMBIOS 信息之前也别联网就行了。

**Comment by ShawLocke** [comment]
> 可以，你安装过程别联网，安装完成之后，没有重新生成 SMBIOS 信息之前也别联网就行了。

昨天为了测试新买的94360cd无线网卡是否能够免驱，已经联网了，但没有登录账户。是不是需要重装一次？
如果不联网，是不是先到其他电脑上下载好Clover Configurator，放到另外一个U盘中，等黑苹果安装完成后，再将这个U盘中的Clover Configurator复制到黑苹果中去使用？

**Comment by andot** [comment]
嗯，是的。你可以试试看。其实我觉得问题不大。修改之后，只要能登录 messages 和 facetime 就行了。
