### ISSUE TITLE
可以给个购买Type-E 转 Type-C的关键词或者链接吗?

### ISSUE THREAD

**Issue by sxdxzkq** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#59]
可以给个购买Type-E 转 Type-C的关键词或者链接吗?
我搜不到...

**Comment by andot** [comment]
淘宝搜索`USB Type-E to Type-C`就可以了

**Comment by sxdxzkq** [comment]
> 淘宝搜索`USB Type-E to Type-C`就可以了

搜到了... 感谢...
