### ISSUE TITLE
反馈升级10.15后目前发现的几个bug

### ISSUE THREAD

**Issue by 597619339** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#6]
1.毛玻璃部分断层又出现了，之前10.14.6时使用dp输出会出现毛玻璃颜色断层，换HDMI后就没事了，现在无论是哪种线都会颜色断层，感觉是显卡驱动没适配好的原因；
2.Sidecar有点异常，连接ipad mini5后，ipad端是黑屏无显示的，但是apple pencil能正常触控，说明是能正常连接上的，但是却没有显示画面

我的配置是
i5 9400f
蓝宝石rx590
微星b360迫击炮

**Comment by andot** [comment]
1、没有 590 显卡，这个我也不知道怎么解决。
2、没用过 Sidecar，拿 ipad 当显示器感觉太奢侈了。

**Comment by 597619339** [comment]
问题解决了，色彩问题注入EDID后一切正常了，sidecar功能需要有核显参与硬解才能使用，换了个8500也正常了，现在完美了～～

**Comment by andot** [comment]
恭喜恭喜~

**Comment by hflyf123** [comment]
> 问题解决了，色彩问题注入EDID后一切正常了，sidecar功能需要有核显参与硬解才能使用，换了个8500也正常了，现在完美了～～

我的cpu是9600k，有核显，显卡是580，但是sidecar ipad还是黑屏，不过侧边栏操作有效，你是咋解决的。

**Comment by 597619339** [comment]
> > 问题解决了，色彩问题注入EDID后一切正常了，sidecar功能需要有核显参与硬解才能使用，换了个8500也正常了，现在完美了～～
> 
> 我的cpu是9600k，有核显，显卡是580，但是sidecar ipad还是黑屏，不过侧边栏操作有效，你是咋解决的。

估计你没有激活核显硬解，去BIOS打开核显看看

**Comment by andot** [comment]
有核显的话，建议改成 iMac19,2，更稳定一些。
