### ISSUE TITLE
请问大家有没有遇到显卡显存爆满的问题

### ISSUE THREAD

**Issue by FFzt** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#68]
1.感谢andot大大的EFI分享
2.修改过很多次机型以及只开启核显/独显，或者核显独显都开启。都遇到了显存占满不释放的问题，请问是否正常，谢谢吖

**Comment by andot** [comment]
![image](https://user-images.githubusercontent.com/232161/76724452-f6f84b00-6785-11ea-9a52-21acf2802ca6.png)
不知道我这个看起来算不算正常？

**Comment by lbq1223android** [comment]
> ![image](https://user-images.githubusercontent.com/232161/76724452-f6f84b00-6785-11ea-9a52-21acf2802ca6.png)
> 不知道我这个看起来算不算正常？

![Xnip2020-03-23_21-13-18](https://user-images.githubusercontent.com/8446745/77320218-22150880-6d4b-11ea-8f01-d281412d93ef.jpg)

我的也是显存爆满

**Comment by andot** [comment]
正常，Mac就不喜欢释放内存，不管显存还是内存。不用了也不释放，留着当缓存。

**Comment by lbq1223android** [comment]
> 正常，Mac就不喜欢释放内存，不管显存还是内存。不用了也不释放，留着当缓存。

针对这个情况 我还做了一些压力测试  包括播放4k什么的 系统一切正常 倒是没出现什么错误

**Comment by FFzt** [comment]
<img width="902" alt="Snipaste_2020-03-29_02-02-51" src="https://user-images.githubusercontent.com/37873312/77830153-84ae4000-7161-11ea-9365-9a61f2ef244a.png">
听你们都这样，应该是正常情况吧，谢谢大家🙏

**Comment by andot** [comment]
@FFzt 你的 RX 580 是怎么调教的，怎么功率比我低一倍。我的最低也是 110W 以上。

**Comment by FFzt** [comment]
> @FFzt 你的 RX 580 是怎么调教的，怎么功率比我低一倍。我的最低也是 110W 以上。

其实我也是刚接触到黑苹果，这也是第一次自己搞黑苹果，用的是你上一个版本的EFI，同时按照你推荐的设置了显卡优化的参数后没做其他处理，日常使用功率都在60W-70W之间。硬件配置我都是按照你的配置单买的，不过我用的是西数黑盘，系统10.15.3，机型iMac Pro (2017)。我也不知道怎么这么低😂
