### ISSUE TITLE
10.15.4升级失败

### ISSUE THREAD

**Issue by guange2015** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#74]
点了更新后，变色龙界面出现两个macos的盘，多的那个叫 Install mac os之类的，进入后会一直卡在白苹果界面，没有进度条，也不会动。

**Comment by guange2015** [comment]
![WechatIMG43](https://user-images.githubusercontent.com/222455/77517896-d7fd6580-6eb7-11ea-9a40-06d367ce2ba7.jpeg)

刚把efi也更新了，但还是进不去，用-v进去的报错信息在上l图

**Comment by andot** [comment]
可能你下载的升级镜像有错误。我直接无痛升级的。

**Comment by guange2015** [comment]
哥们，有解决办法吗，怎么删除重新下载更新？

**Comment by guange2015** [comment]
其实当时还有个严重问题，BIOS貌似损坏了，强制进入了bios界面给我恢复了才能进入引导界面的。

**Comment by andot** [comment]
BIOS 只是重置了，如果是这样的话，你需要重新设置一下 BIOS。有些选项你需要重新打开，有些选项要关闭。

**Comment by guange2015** [comment]
更新了github最新文件后，我的问题解决了。 因为我用cc查看了当前是5106，在黑果小兵上有人提到要5107才行。

**Comment by andot** [comment]
我是在5106下直接升级成功的，升级完之后，我才更新的5107。看来我运气不错😄
