### ISSUE TITLE
请问我在重建驱动缓存遇到了这样的情况是怎么回事？图一卡在一半然后就变成图二了。  `

### ISSUE THREAD

**Issue by shihaonan2020** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#78]

**Comment by shihaonan2020** [comment]
![P00328-222515(1)](https://user-images.githubusercontent.com/62801921/77837659-3bc8ac80-719e-11ea-9729-f322015e982a.jpg)
![P00328-222530(1)](https://user-images.githubusercontent.com/62801921/77837660-42572400-719e-11ea-9ae1-f49c0507168b.jpg)

**Comment by andot** [comment]
应该是完成了吧
