### ISSUE TITLE
开机第二阶段黑屏直接进系统

### ISSUE THREAD

**Issue by CCCChen1** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#82]
您好，谢谢您对这个项目的贡献 已经成功吃上了黑苹果
但是有点小问题
开机Apple logo走完一半进度条之后黑屏直接进入系统了
想请教一下 怎样才能让进度条完整走完进入系统

**Comment by andot** [comment]
多装点软件，然后关机之前多打开一些软件，关机的时候选择再次登录时重新打开窗口，这样再次开机的时候，就能在黑屏之后，会等到进度条再次显示出来，然后跑完进度条再进系统了。如果还不行的话，那关机前再多打开一点软件。

**Comment by CCCChen1** [comment]
好的 谢谢 我去试一下

**Comment by CCCChen1** [comment]
您好 又发现了一个问题 机箱面板有两个usb3.0只有一个可以正常读取，另一个无法读取usb3.0但是可以正常读取usb2.0 请问该怎样操作可以使得两个usb3.0接口都能够正常工作

**Comment by andot** [comment]
大概是供电不足吧，这个我也没办法。

**Comment by CCCChen1** [comment]
好滴 谢谢
