### ISSUE TITLE
开启了文件保险箱，无法引导。

### ISSUE THREAD

**Issue by guange2015** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#87]
搜索到一些资料，引导时f3可以看到盘符，但还是引导不进去。 -v显示打开文件错误之类的。

**Comment by guange2015** [comment]
已解决，写下方案

在windows下使用DiskGenius打开EFI分区
将 clover/dirvers/off中的7个文件拷到uefi中

AppleImageCodec-64.efi
AppleKeyAggregator-64.efi
AppleKeyFeeder-64.efi
AppleUITheme-64.efi
AptioInputFix-64.efi
FirmwareVolume-64.efi
HashServiceFix-64.efi

然后在clover启动界面按F3，会见到你的苹果启动菜单，然后引导超级慢，慢慢等。

参考了这个文案
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1847182

**Comment by andot** [comment]
这个功能建议不要开，安全的代价可能是数据全失。

**Comment by guange2015** [comment]
是的，没有特殊要求最好不要开，我特地提前做好了timemachine.
