### ISSUE TITLE
关机后机箱led常亮

### ISSUE THREAD

**Issue by cclucky1** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#88]
老哥最近发现关机后机箱的led指示灯不会熄灭
这种情况是最近出现 而我未对任何文件进行修改
请教一下这是怎么回事

**Comment by andot** [comment]
没遇到过的问题，我也不知道怎么回事。

**Comment by cclucky1** [comment]
已经找到方法解决 关闭BIOS的erp ready
