### ISSUE TITLE
RX5500xt如何驱动

### ISSUE THREAD

**Issue by lclancey** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#90]
请问下 RX470矿卡之前没问题 现在换了RX5500xt 华擎的挑战者8G 请问这个应该如何驱动
现在的版本读条之后黑屏

**Comment by lclancey** [comment]
找到了 远景说参数加一条agdpmod=pikera即可

**Comment by lclancey** [comment]
又有问题了....BCM94352z驱动不起来
网卡是从笔记本上拆下来的联想版BCM94352z,Win下正常使用, Mac下尝试了驱动, 但是只能看到wifi图标, 连接不上
蓝牙我是按照 `https://github.com/acidanthera/BrcmPatchRAM`的说明做的, 把`BrcmPatchRAM3.kext`,`BrcmFirmwareRepo.kext`,`BrcmBluetoothInjector.kext`放到/L/E里, 但是重建缓存一直提示`Kext with invalid signature (-67062) allowed` 然后也不显示蓝牙图标
请问有什么办法吗?实在不行只能购买这个EFI的同款了...

**Comment by andot** [comment]
这个网卡没折腾过，真不清楚。
