### ISSUE TITLE
关机后按任意键开机

### ISSUE THREAD

**Issue by cclucky1** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#91]
老哥有没有遇到过这个问题,就是说正常关机之后 按鼠标 或者键盘的任意键都会开机,想请教一下是config.plist的问题还是BIOS设置的问题 
| 主板       | **微星（MSI）B360M MORTAR迫击炮**                            |
| :--------- | ------------------------------------------------------------ |
| **CPU**    | **英特尔（Intel）i5 9400F 酷睿六核 盒装CPU处理器**           |
| **内存**   | **（Team）DDR4 3000 16G（8G\*2)**                            |
| **显卡**   | **（yeston） RX580-2048SP 8G D5 大地之神 1284MHz/7GHz 8GB/256bit GDDR5（刷RX570 VBIOS）** |
| **硬盘**   | **（HIKVISION）512GB SSD固态硬盘 M.2接口(NVMe协议) CRUIS系列C2000Pro（第一批东芝颗粒）** |
| **散热**   | **利民（Thermalright）AS120PLUS 刺灵 CPU风冷散热器 双平台**  |
| **网卡**   | **BCM94360CD**                                               |
| **机箱**   | **乔思伯（JONSBO）C3-PLUS银色 M-ATX机箱**                    |
| **显示器** | **AOC Q2490PXQ 23.8英寸 IPS 2K高清 微边框 低蓝光**           |

**Comment by andot** [comment]
应该是BIOS设置问题
