### ISSUE TITLE
可以更新10.15.5了嘛

### ISSUE THREAD

**Issue by cclucky1** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#93]
有没有大佬解答一下,现在15.4关机程序坞卡重叠好烦啊想升级

**Comment by andot** [comment]
不知道，我还没升级到 10.15.5。

**Comment by guange2015** [comment]
我来做下勇士

**Comment by guange2015** [comment]
![image](https://user-images.githubusercontent.com/222455/83098180-78505000-a0dc-11ea-9b96-e2a373476b4a.png)
直接升级了，没遇到什么问题。

**Comment by andot** [comment]
好了，我也升级了，没有问题。EFI 内容也更新了一下。
