### ISSUE TITLE
提示双硬解了，播放4k还是卡

### ISSUE THREAD

**Issue by 445022889** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#95]
硬件配置：
主板：微星 B360M 迫击炮
CPU： Intel Core i5-9600k
显卡：迪兰 RX580 8G 2304SP
VideoProc提示双解了，结果从网上找的4k 60fps的样片播放，前面播放还行，但是一会就不行了，用鼠标点着播放 也是会卡顿一下
之前用的oc刷的下面的efi
https://github.com/GeQ1an/MSI-B360M-MORTAR-HACKINTOSH-OPENCORE-EFI
有问题，就刷了现在的这个efi，非常好，其他都正常，就是会卡顿，请问我需要怎么操作呀

**Comment by andot** [comment]
换个播放器试试看

**Comment by 445022889** [comment]
> 换个播放器试试看

用自带的quicktime是有这个情况，然后下载了一个估计直接走的软解，更卡，有推荐的吗

**Comment by andot** [comment]
那是不是你的机器本身播放这个片就卡啊？
