### ISSUE TITLE
显示器线应该插在主板还是独显上面

### ISSUE THREAD

**Issue by Fre-ak** [andot/MSI-B360M-MORTAR-IMACPRO-EFI#99]
现在是插在独显上面  但直到进入系统才有画面

**Comment by andot** [comment]
有独显，肯定是查到独显上面。你看看 BIOS 里面有没有把独显设置为开机显卡。

**Comment by Fre-ak** [comment]
比较好奇你是怎么设置的, 我的主板也是b360m迫击炮,机型是iMac19,2
如果把独显设为开机显卡,  videoproc 显示不了显卡型号, 并且硬解都显示不可用, 经查应该是核显没打开
将核显设为开机显卡, videoproc 显示 hd630, 硬解正常, 但直到进入系统才出现画面

**Comment by andot** [comment]
把独显设置为开机显卡，开机显卡下面还有个选项也打开，打开之后最下面会有一个64MB的选项。

**Comment by Fre-ak** [comment]
成功了 十分感谢🙏
